version: "3.8"
services:
  backend:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    command: uvicorn backend.main:app --host 0.0.0.0 --port 8000
  frontend:
    working_dir: /app/frontend
    image: node:18
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    command: sh -c "npm install && npm run dev"